import React, { useState } from 'react';
import { Player } from '../../types';
import { BureauAvatar } from '../common/BureauAvatar';
import { sound } from '../../sound/audioEngine';
import { ShieldAlert } from 'lucide-react';

interface BureauReviewModalProps { trailingPlayer: Player; onSelectOption: (optionType: 'SAFE'|'RISKY'|'QUESTIONABLE', scoreDelta:number)=>void; onClose:()=>void; }
type ReviewType='SAFE'|'RISKY'|'QUESTIONABLE';
const REVIEW_ART:Record<ReviewType,string>={SAFE:'/assets/generated/review/safe.jpg',RISKY:'/assets/generated/review/risky.jpg',QUESTIONABLE:'/assets/generated/review/deeply-questionable.jpg'};

export const BureauReviewModal:React.FC<BureauReviewModalProps>=({trailingPlayer,onSelectOption,onClose})=>{
  const [selectedFile,setSelectedFile]=useState<ReviewType|null>(null);const[resolvedDelta,setResolvedDelta]=useState<number|null>(null);const[outcomeText,setOutcomeText]=useState('');
  const pick=(type:ReviewType)=>{sound.playStamp();setSelectedFile(type);if(type==='SAFE'){setResolvedDelta(180);setOutcomeText('Guaranteed relief: +180 points. Dull, dependable and almost aggressively sensible.');return;}const roll=Math.random();if(type==='RISKY'){const ok=roll<.58;setResolvedDelta(ok?520:0);setOutcomeText(ok?'The Treasury has inexplicably approved the claim: +520 points.':'Application rejected. +0 points. The risk assessment was, in retrospect, quite clear.');return;}const ok=roll<.38;setResolvedDelta(ok?650:-140);setOutcomeText(ok?'Executive overreach has succeeded. 650 points will be seized from the current leader if available.':'Executive overreach has failed. A 140-point administrative penalty has been attached.');};
  const confirm=()=>{if(selectedFile&&resolvedDelta!==null)onSelectOption(selectedFile,resolvedDelta)};
  return <div className="fixed inset-0 z-50 bg-[#183138]/80 backdrop-blur-md flex items-center justify-center p-4"><div className="bureau-paper border-[4px] border-[#765139] w-full max-w-4xl rounded-[28px] shadow-2xl overflow-hidden bureau-paper-drop"><div className="bg-[#e0a83f] px-6 py-4 border-b-[3px] border-[#765139] flex items-center gap-3 text-[#463421]"><ShieldAlert size={24}/><BureauAvatar player={trailingPlayer} size={46}/><div><h3 className="font-['Cinzel'] font-black text-lg uppercase">Bureau Review</h3><p className="font-['Courier_Prime'] text-[11px]">Emergency intervention for <strong>{trailingPlayer.name}</strong></p></div></div><div className="p-6 space-y-5"><p className="rounded-xl border-2 border-[#b48f61] bg-[#efe0ba] p-3.5 font-['Courier_Prime'] text-xs text-[#604936] italic">The Bureau has reviewed your position and concluded that natural recovery is becoming statistically optimistic. One intervention is authorised.</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{(['SAFE','RISKY','QUESTIONABLE'] as ReviewType[]).map(type=><button key={type} disabled={resolvedDelta!==null} onClick={()=>pick(type)} className={`bureau-button overflow-hidden rounded-2xl border-[3px] border-[#765139] bg-[#fff7df] text-left ${selectedFile===type?'ring-4 ring-[#2f8f95]/50':''}`}><img src={REVIEW_ART[type]} alt="" className="h-44 w-full object-cover"/><div className="p-3"><strong className="font-['Cinzel'] text-sm text-[#244b55]">{type==='QUESTIONABLE'?'Deeply Questionable':type}</strong><p className="mt-1 text-xs text-[#665348]">{type==='SAFE'?'Guaranteed +180.':type==='RISKY'?'58% chance of +520.':'38% chance to seize 650; failure costs 140.'}</p></div></button>)}</div>{resolvedDelta!==null&&<div className="bureau-stamp-in rounded-xl border-[3px] border-[#765139] bg-[#244b55] p-4 text-center font-['Courier_Prime'] text-sm text-[#fff7df]">{outcomeText}</div>}<div className="flex justify-between items-center"><button onClick={onClose} className="text-xs font-['Courier_Prime'] text-[#765b45]">Decline intervention</button><button disabled={resolvedDelta===null||!selectedFile} onClick={confirm} className="bureau-button rounded-xl bg-[#d9644f] px-6 py-3 text-white font-['Cinzel'] font-black text-xs uppercase tracking-widest disabled:opacity-40">File Outcome</button></div></div></div></div>;
};
