import React, { useState } from 'react';
import { ClosestWinsChallenge, Player } from '../../types';
import { sound } from '../../sound/audioEngine';
import { Calculator, EyeOff, ArrowRight } from 'lucide-react';
import { CommentaryPlaque } from '../common/CommentaryPlaque';
import { ApparatusFrame } from '../common/ApparatusFrame';
import { scoreEstimate } from '../../game/scoring';

interface ClosestWinsProps { challenge: ClosestWinsChallenge; players: Player[]; onCompleteRound: (playerScores: Record<string, number>, errors: Record<string, number>) => void; }

export const ClosestWinsRound: React.FC<ClosestWinsProps> = ({challenge,players,onCompleteRound}) => {
  const [playerInputs,setPlayerInputs]=useState<Record<string,number>>({}); const [currentInputIdx,setCurrentInputIdx]=useState(0); const [currentGuessString,setCurrentGuessString]=useState(''); const [isRevealed,setIsRevealed]=useState(false); const [scoresComputed,setScoresComputed]=useState<Record<string,number>>({}); const [errorsComputed,setErrorsComputed]=useState<Record<string,number>>({});
  const activePlayer=players[currentInputIdx]||players[0]; if(!activePlayer)return null;
  const compute=(inputs:Record<string,number>)=>{const scores:Record<string,number>={};const errors:Record<string,number>={};players.forEach(p=>{const guess=inputs[p.id]??0;const error=(Math.abs(guess-challenge.correctValue)/Math.max(Math.abs(challenge.correctValue),1))*100;errors[p.id]=error;scores[p.id]=scoreEstimate(error,challenge.toleranceScale)});setScoresComputed(scores);setErrorsComputed(errors);setIsRevealed(true);sound.playVictoryFanfare()};
  const submit=(e?:React.FormEvent)=>{e?.preventDefault();const val=parseFloat(currentGuessString.trim());if(Number.isNaN(val))return;sound.playStamp();const next={...playerInputs,[activePlayer.id]:val};setPlayerInputs(next);setCurrentGuessString('');if(currentInputIdx+1<players.length)setCurrentInputIdx(i=>i+1);else compute(next)};
  const best=players.reduce<Player|null>((b,p)=>!b||(scoresComputed[p.id]??0)>(scoresComputed[b.id]??0)?p:b,null);
  if(isRevealed)return <div className="space-y-5"><ApparatusFrame eyebrow="Statistics Office • Metric Comparison Engine" title={`${challenge.correctValue.toLocaleString()} ${challenge.unitSuffix||challenge.unit}`} subtitle="The certified value has been released. The machinery will now compare everybody's optimism with reality." icon={<Calculator size={28}/>} accent="#3f9b74" instrumentLabel="METRIC ENGINE"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{players.map(p=><div key={p.id} className="rounded-2xl border-[4px] border-[#65442c] bg-[#fff5d8] p-4 shadow-[0_5px_0_#65442c]"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="text-3xl">{p.avatar}</span><div><div className="font-['Cinzel'] font-black text-[#30434a]">{p.name}</div><div className="font-['Space_Mono'] text-sm text-[#715844]">Guess {playerInputs[p.id]?.toLocaleString()}</div></div></div><div className="rounded-xl border-2 border-[#65442c] bg-[#3f9b74] px-3 py-2 text-center text-white"><div className="font-['Space_Mono'] text-2xl font-black">{scoresComputed[p.id]??0}</div><div className="font-['Courier_Prime'] text-[8px] font-black">{(errorsComputed[p.id]??0).toFixed(1)}% ERROR</div></div></div></div>)}</div></ApparatusFrame><CommentaryPlaque score={best?(scoresComputed[best.id]??0):0} playerName={best?.name??'Candidates'} roundType="CLOSEST_WINS" questionPrompt={challenge.prompt} explanation={challenge.explanation} source={challenge.source} errorPercent={best?errorsComputed[best.id]:undefined} isCorrect={true} onProceed={()=>onCompleteRound(scoresComputed,errorsComputed)}/></div>;
  return <div className="w-full max-w-4xl mx-auto font-['Plus_Jakarta_Sans']"><ApparatusFrame eyebrow="Statistics Office • Confidential Metric Engine" title={challenge.prompt} subtitle="Each estimate is sealed before the next candidate approaches the machine." icon={<Calculator size={28}/>} accent="#3f9b74" instrumentLabel="CALIBRATOR"><div className="grid grid-cols-1 lg:grid-cols-[1fr_330px] gap-6 items-center"><div className="rounded-[28px] border-[5px] border-[#65442c] bg-[#3f9b74] p-5 shadow-[inset_0_0_0_5px_#8bc4a8,0_10px_0_#65442c]"><div className="rounded-[22px] border-[4px] border-[#65442c] bg-[#fff3cf] p-6 text-center shadow-inner"><div className="mx-auto mb-5 flex h-28 w-28 items-center justify-center rounded-full border-[8px] border-[#314a50] bg-[#e4d8b8] text-[#314a50] shadow-[inset_0_0_0_5px_#f1cf66]"><Calculator size={48}/></div><div className="grid grid-cols-5 gap-2">{[0,25,50,75,100].map(n=><div key={n} className="rounded-lg border-2 border-[#65442c] bg-[#f1cf66] py-2 font-['Space_Mono'] text-xs font-bold text-[#60462f]">{n}</div>)}</div><div className="mt-4 font-['Courier_Prime'] text-[9px] font-black uppercase tracking-[.2em] text-[#705943]">sealed estimate intake • no peeking</div></div></div><div className="rounded-2xl border-[4px] border-[#65442c] bg-[#fff5d8] p-5 shadow-[0_7px_0_#65442c]"><div className="mb-4 flex items-center gap-3 rounded-xl border-2 border-[#65442c] bg-[#4c82c3] p-3 text-white shadow-[0_4px_0_#65442c]"><span className="text-3xl">{activePlayer.avatar}</span><div><div className="font-['Courier_Prime'] text-[9px] font-black uppercase tracking-widest">Candidate {currentInputIdx+1} of {players.length}</div><div className="font-['Cinzel'] font-black">{activePlayer.name}</div></div></div><div className="mb-4 flex items-center gap-2 rounded-lg bg-[#eee0ba] p-3 font-['Courier_Prime'] text-[10px] text-[#654a34]"><EyeOff size={16}/>Previous estimates sealed</div><form onSubmit={submit} className="space-y-3"><input type="number" step="any" autoFocus value={currentGuessString} onChange={e=>setCurrentGuessString(e.target.value)} placeholder={`Estimate in ${challenge.unit}`} className="w-full rounded-xl border-[3px] border-[#65442c] bg-[#fffaf0] px-4 py-4 font-['Space_Mono'] text-xl text-[#30434a] outline-none focus:border-[#3f9b74]"/><button disabled={!currentGuessString.trim()} className="flex w-full items-center justify-center gap-2 rounded-xl border-[3px] border-[#65442c] bg-[#e65d4e] py-4 font-['Cinzel'] text-xs font-black uppercase text-white shadow-[0_5px_0_#65442c]"><span>Seal Estimate</span><ArrowRight size={16}/></button></form></div></div></ApparatusFrame></div>;
};
