import React, { useState } from 'react';
import { Check, Gavel, Send } from 'lucide-react';
import type { AdjudicationRecord, Player, PutUpOrShutUpChallenge } from '../../types';
import { sound } from '../../sound/audioEngine';
import { scoreBidSuccess } from '../../game/scoring';
import { ApparatusFrame } from '../common/ApparatusFrame';
import { CommentaryPlaque } from '../common/CommentaryPlaque';
import { findAnswerMatch, normalizeAnswer } from '../../game/answerMatching';
import { HostAdjudicationPanel } from '../common/HostAdjudicationPanel';
import { AdjudicationReceipt } from '../common/AdjudicationReceipt';

interface Props { challenge: PutUpOrShutUpChallenge; players: Player[]; currentPlayerIndex: number; onComplete: (winnerId: string, score: number) => void; onAdjudication:(record:Omit<AdjudicationRecord,'challengeId'|'recordedAt'>)=>void; onUndoAdjudication:()=>void; }

interface ExecutionSnapshot { phase:'BIDDING'|'EXECUTION'|'SUMMARY'; answersGiven:string[]; inputValue:string; feedback:string|null; isSuccess:boolean|null; finalScore:number; fatalAnswer:string|null; pendingAnswer:string|null }

export const PutUpOrShutUpRound: React.FC<Props> = ({ challenge, players, currentPlayerIndex, onComplete, onAdjudication, onUndoAdjudication }) => {
  const [phase, setPhase] = useState<'BIDDING'|'EXECUTION'|'SUMMARY'>('BIDDING');
  const [currentBid, setCurrentBid] = useState(0);
  const [highestBidderIndex, setHighestBidderIndex] = useState(-1);
  const [passedPlayerIds, setPassedPlayerIds] = useState<string[]>([]);
  const [turnIndex, setTurnIndex] = useState(currentPlayerIndex);
  const [answersGiven, setAnswersGiven] = useState<string[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [feedback, setFeedback] = useState<string|null>(null);
  const [isSuccess, setIsSuccess] = useState<boolean|null>(null);
  const [finalScore, setFinalScore] = useState(0);
  const [fatalAnswer, setFatalAnswer] = useState<string|null>(null);
  const [pendingAnswer,setPendingAnswer]=useState<string|null>(null);
  const [lastRuling,setLastRuling]=useState<{reason:string;snapshot:ExecutionSnapshot}|null>(null);
  const activeBidder = players[turnIndex % (players.length || 1)] || players[0];
  const winningPlayer = (highestBidderIndex >= 0 ? players[highestBidderIndex] : players[0]) || activeBidder;
  if (!activeBidder || !winningPlayer) return null;

  const advance = (passed: string[]) => { let next = turnIndex + 1, attempts = 0; while (passed.includes(players[next % players.length].id) && attempts < players.length) { next += 1; attempts += 1; } setTurnIndex(next); };
  const bid = (amount: number) => { const capped = Math.min(challenge.validAnswers.length, amount); sound.playDepartmentCue('PUT_UP_OR_SHUT_UP', 'PROCESSING'); setCurrentBid(capped); setHighestBidderIndex(turnIndex % players.length); if (players.length === 1 || capped >= challenge.validAnswers.length) { setPhase('EXECUTION'); return; } advance(passedPlayerIds); };
  const pass = () => { sound.playDepartmentCue('PUT_UP_OR_SHUT_UP', 'MOVE'); const nextPassed = [...passedPlayerIds, activeBidder.id]; setPassedPlayerIds(nextPassed); const remaining = players.filter(player => !nextPassed.includes(player.id)); if ((remaining.length <= 1 && currentBid > 0) || nextPassed.length >= players.length) { if (currentBid === 0) { setCurrentBid(1); setHighestBidderIndex(currentPlayerIndex); } setPhase('EXECUTION'); return; } advance(nextPassed); };
  const snapshot=():ExecutionSnapshot=>({phase,answersGiven:[...answersGiven],inputValue,feedback,isSuccess,finalScore,fatalAnswer,pendingAnswer});
  const undoLastRuling=()=>{if(!lastRuling)return;const prior=lastRuling.snapshot;setPhase(prior.phase);setAnswersGiven(prior.answersGiven);setInputValue(prior.inputValue);setFeedback(prior.feedback);setIsSuccess(prior.isSuccess);setFinalScore(prior.finalScore);setFatalAnswer(prior.fatalAnswer);setPendingAnswer(prior.pendingAnswer);setLastRuling(null);onUndoAdjudication();};
  const acceptAnswer=(answer:string,submitted:string,decision:'AUTOMATIC'|'HOST_ACCEPTED'|'HOST_EDITED',reason:string)=>{setLastRuling({reason,snapshot:snapshot()});sound.playDepartmentCue('PUT_UP_OR_SHUT_UP', 'ACCEPTED');const updated=[...answersGiven,answer];setAnswersGiven(updated);setInputValue('');setPendingAnswer(null);setFeedback(`Accepted: ${answer} (${updated.length}/${currentBid})`);onAdjudication({playerId:winningPlayer.id,submittedAnswer:submitted,acceptedAnswer:answer,decision,reason});if(updated.length>=currentBid){sound.playDepartmentCue('PUT_UP_OR_SHUT_UP', 'RESULT');setFinalScore(scoreBidSuccess(currentBid,challenge.validAnswers.length));setIsSuccess(true);setPhase('SUMMARY');}};
  const rejectAnswer=(raw:string)=>{const reason='The host rejected the unmatched answer after reviewing the contract register.';setLastRuling({reason,snapshot:snapshot()});sound.playDepartmentCue('PUT_UP_OR_SHUT_UP', 'REJECTED');setPendingAnswer(null);setFatalAnswer(raw);setFeedback(`“${raw}” rejected. Contract collapsed.`);setFinalScore(0);setIsSuccess(false);setPhase('SUMMARY');onAdjudication({playerId:winningPlayer.id,submittedAnswer:raw,decision:'HOST_REJECTED',reason});};
  const submit = (event?: React.FormEvent) => { event?.preventDefault(); const raw=inputValue.trim(); if(!raw)return;if(answersGiven.some(answer=>normalizeAnswer(answer)===normalizeAnswer(raw))){setFeedback(`“${raw}” was already entered.`);setInputValue('');return;}const result=findAnswerMatch(raw,challenge.validAnswers);if(result.candidate)acceptAnswer(result.candidate.name,raw,'AUTOMATIC',result.reason);else setPendingAnswer(raw);};
  const bids = [1,2,3].map(increment => Math.min(challenge.validAnswers.length, currentBid + increment)).filter((value,index,all) => value > currentBid && all.indexOf(value) === index);
  const claimLadder = Array.from({ length: Math.min(10, challenge.validAnswers.length) }, (_, index) => index + 1);

  if (phase === 'SUMMARY') return <div className="space-y-5"><ApparatusFrame compact state="RESULT" eyebrow="High Bidding Chamber • Contract adjudicated" title={isSuccess ? 'Contract fulfilled' : 'Contract defaulted'} subtitle={`${winningPlayer.name} held the final claim of ${currentBid}.`} icon={<Gavel size={28}/>} accent="#b94f58" instrumentLabel="CONTRACT RESULT"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border-[3px] border-[#65442c] bg-[#f3d66d] p-3 text-center font-['Space_Mono'] font-black">CLAIM {currentBid}</div><div className={`rounded-xl border-[3px] border-[#65442c] p-3 text-center font-['Space_Mono'] font-black text-white ${isSuccess?'bg-[#3f9b74]':'bg-[#e65d4e]'}`}>{answersGiven.length} FILED</div></div></ApparatusFrame><CommentaryPlaque score={finalScore} playerName={winningPlayer.name} roundType="PUT_UP_OR_SHUT_UP" questionPrompt={challenge.prompt} explanation={challenge.explanation} source={challenge.source} playerAnswer={isSuccess ? `${answersGiven.length} valid answers delivered` : fatalAnswer ?? undefined} correctAnswer={`Contract required ${currentBid} valid ${challenge.targetUnit}`} history={winningPlayer.stats} isCorrect={isSuccess === true} adjudicationReason={lastRuling?.reason} onUndoLastRuling={lastRuling?undoLastRuling:undefined} onProceed={() => onComplete(winningPlayer.id, finalScore)}/></div>;

  return <div className="mx-auto w-full max-w-5xl font-['Plus_Jakarta_Sans']"><ApparatusFrame eyebrow="High Bidding Chamber • Contract Desk" title={challenge.prompt} subtitle="Claim how many valid answers you can name. The highest bidder must then prove it without making a single mistake." icon={<Gavel size={28}/>} accent="#b94f58" instrumentLabel="BID CONSOLE"><div className="grid grid-cols-1 items-center gap-6 lg:grid-cols-[minmax(0,1fr)_370px]">
    <div className="relative overflow-hidden rounded-[28px] border-[5px] border-[#65442c] bg-[#7e3340]/90 p-5 shadow-[inset_0_0_0_5px_#df9197,0_10px_0_#65442c]"><div className="relative rounded-[22px] border-[4px] border-[#65442c] bg-[#fff1cc]/90 p-5 shadow-inner backdrop-blur-[1px]">
      <div className="mb-4 grid grid-cols-3 gap-2 rounded-xl border-[3px] border-[#65442c] bg-[#294b55] p-2 text-center font-['Courier_Prime'] text-xs font-black uppercase text-[#f8e4a1]"><span>1. Make a claim</span><span>2. Highest bid plays</span><span>3. One error fails</span></div>
      <div className="bureau-claim-ladder mx-auto max-w-md" aria-label={`Current claim ${currentBid}`}>
        {claimLadder.map(value => <div key={value} className={`bureau-claim-rung ${value===currentBid?'bureau-claim-rung--current':''} ${value<currentBid?'bureau-claim-rung--passed':''}`}><span>{value}</span><i/></div>)}
      </div>
      <div className="mt-2 text-center"><div className="font-['Cinzel'] font-black text-[#30434a]">{currentBid === 0 ? 'Awaiting opening claim' : `${currentBid} ${challenge.targetUnit} required`}</div>{currentBid > 0 && <div className="font-['Courier_Prime'] text-xs font-bold text-[#3f8f6d]">Worth {scoreBidSuccess(currentBid,challenge.validAnswers.length)} points if completed</div>}{highestBidderIndex >= 0 && <div className="mt-1 font-['Courier_Prime'] text-xs font-black uppercase text-[#a9443d]">Contract held by {players[highestBidderIndex].name}</div>}</div>
      <div className={`mt-5 grid gap-2 ${players.length === 1 ? 'grid-cols-1' : players.length === 2 ? 'grid-cols-2' : 'grid-cols-4'}`}>{players.map((player,index) => <div key={player.id} className={`relative rounded-lg border-2 border-[#65442c] p-2 text-center ${passedPlayerIds.includes(player.id) ? 'bg-[#bcae91] text-[#725f49] opacity-60' : index === turnIndex % players.length ? 'bg-[#2fa8ae] text-white' : 'bg-[#ead9b3] text-[#60452f]'}`}><div className="text-xl">{player.avatar}</div><div className="truncate font-['Courier_Prime'] text-xs font-black">{player.name}</div>{passedPlayerIds.includes(player.id) && <span className="absolute right-1 top-1 rounded bg-[#a9443d] px-1 font-['Courier_Prime'] text-[7px] text-white">PASSED</span>}</div>)}</div>
    </div></div>
    <div className="relative overflow-hidden rounded-2xl border-[4px] border-[#65442c] bg-[#fff5d8]/95 p-5 shadow-[0_7px_0_#65442c]"><div className="relative z-10">{phase === 'BIDDING' ? <div className="space-y-4">
      <div className="rounded-xl border-2 border-[#65442c] bg-[#2fa8ae] p-3 text-white shadow-[0_4px_0_#65442c]"><div className="font-['Courier_Prime'] text-xs font-black uppercase tracking-widest">Your turn to claim</div><div className="font-['Cinzel'] text-lg font-black">{activeBidder.name}</div><div className="mt-1 font-['Fraunces'] text-xs">How many valid answers can you name?</div></div>
      <div className={`grid gap-2 ${bids.length === 1 ? 'grid-cols-1' : bids.length === 2 ? 'grid-cols-2' : 'grid-cols-3'}`}>{bids.map(value => <button key={value} onClick={() => bid(value)} aria-label={`Claim ${value} ${challenge.targetUnit}`} className="bureau-button rounded-xl border-[3px] border-[#65442c] bg-[#f3d66d] px-2 py-3 text-[#60462f]"><strong className="block font-['Cinzel'] text-sm font-black">I can name {value}</strong><span className="mt-1 block font-['Courier_Prime'] text-xs font-bold uppercase">{scoreBidSuccess(value,challenge.validAnswers.length)} pts</span></button>)}</div>
      <div className="rounded-lg border-2 border-dashed border-[#b6925b] bg-[#eee0ba] p-2 text-center font-['Courier_Prime'] text-xs text-[#654a34]">Choose a higher claim, or pass and leave the contract to another candidate.</div><button onClick={pass} className="bureau-button w-full rounded-xl border-[3px] border-[#65442c] bg-[#e65d4e] py-3 font-['Cinzel'] text-xs font-black uppercase text-white">Pass this contract</button>
    </div> : <div className="space-y-4"><div className="rounded-xl border-2 border-[#65442c] bg-[#f3d66d] p-3 text-center text-[#60462f]"><div className="font-['Courier_Prime'] text-xs font-black uppercase">Contract holder</div><div className="font-['Cinzel'] font-black">{winningPlayer.name}</div><div className="font-['Space_Mono'] text-xl font-black">{answersGiven.length} / {currentBid}</div></div><div className="flex flex-wrap gap-2">{Array.from({length:currentBid}).map((_,index) => <span key={index} className={`flex h-9 w-9 items-center justify-center rounded-lg border-2 border-[#65442c] ${index < answersGiven.length ? 'bg-[#3f9b74] text-white' : 'bg-[#ead9b3] text-[#76583f]'}`}>{index < answersGiven.length ? <Check size={16}/> : index + 1}</span>)}</div>{feedback && <div className="rounded-lg bg-[#eee0ba] p-3 font-['Courier_Prime'] text-xs text-[#654a34]">{feedback}</div>}{lastRuling&&!pendingAnswer&&<AdjudicationReceipt reason={lastRuling.reason} onUndo={undoLastRuling}/>} {pendingAnswer?<HostAdjudicationPanel submittedAnswer={pendingAnswer} suggestions={challenge.validAnswers.map(item=>item.name)} onAccept={(answer,edited)=>{const result=findAnswerMatch(answer,challenge.validAnswers);const accepted=result.candidate?.name??answer;acceptAnswer(accepted,pendingAnswer,edited?'HOST_EDITED':'HOST_ACCEPTED',edited?`The host edited the entry to ${accepted} and accepted it.`:`The host accepted the unmatched entry as ${accepted}.`)}} onReject={()=>rejectAnswer(pendingAnswer)}/>:<form onSubmit={submit} className="space-y-3"><input autoFocus value={inputValue} onChange={event => setInputValue(event.target.value)} placeholder="Enter valid answer…" aria-label="Contract answer" className="min-h-11 w-full rounded-xl border-[3px] border-[#65442c] bg-[#fffaf0] px-4 py-3 text-[#30434a] outline-none focus:border-[#2fa8ae]"/><button disabled={!inputValue.trim()} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border-[3px] border-[#65442c] bg-[#2fa8ae] py-3 font-['Cinzel'] text-xs font-black uppercase text-white shadow-[0_4px_0_#65442c]"><Send size={16}/> Verify Answer</button></form>}</div>}</div></div>
  </div></ApparatusFrame></div>;
};
