import React, { useMemo, useState } from 'react';
import { Archive, ArrowRight, CircleDot, FileArchive, Gauge, ShieldQuestion } from 'lucide-react';
import type { BureauAssetKey, Player } from '../../types';
import { HIGHER_LOWER_PROMPTS, randomAsset, type MiniGameType } from '../../data/miniGames';
import { EVENT_ART } from '../../data/visualAssets';
import { GeneratedArtBackdrop } from '../common/GeneratedArtBackdrop';
import { BureauAvatar } from '../common/BureauAvatar';
import { sound } from '../../sound/audioEngine';

export interface MiniGameEffect { playerId: string; pointsDelta?: number; asset?: BureauAssetKey; priorityNextRound?: boolean; note: string; }
interface InterstitialMiniGameProps { type: MiniGameType; players: Player[]; onComplete: (effects: MiniGameEffect[]) => void; }
type ChoiceOutcome = { pointsDelta?: number; asset?: BureauAssetKey; label: string; };
const shuffle = <T,>(items: T[]): T[] => [...items].sort(() => Math.random() - 0.5);
const buildChoiceOutcomes = (type: MiniGameType, count: number): ChoiceOutcome[] => type === 'RED_BUTTON'
  ? shuffle([{ pointsDelta:318,label:'+318 points. A suspiciously productive button.'},{ pointsDelta:173,label:'+173 points. Administrative excitement remains limited.'},{ asset:randomAsset(),label:'A Bureau Asset has dropped out of the machinery.'},{ pointsDelta:-91,label:'−91 points. The red button was red for a reason.' }]).slice(0,count)
  : shuffle([{ asset:randomAsset(),label:'The drawer contains a Bureau Asset.'},{ pointsDelta:264,label:'+264 points were filed here for reasons nobody can explain.'},{ pointsDelta:121,label:'+121 points. A modest but legally defensible discovery.'},{ asset:'PRIORITY_ACCESS' as BureauAssetKey,label:'Priority Access clearance. Keep it until you decide a queue no longer applies to you.' }]).slice(0,count);
const comparisonLabels=(prompt:string):[string,string]=>{const p=prompt.toLowerCase();if(p.includes('north')||p.includes('south'))return['Further North','Further South'];if(p.includes('longer')||p.includes('shorter'))return['Longer','Shorter'];if(p.includes('deeper')||p.includes('shallower'))return['Deeper','Shallower'];if(p.includes('taller'))return['Taller','Shorter'];return['Higher','Lower'];};

export const InterstitialMiniGame: React.FC<InterstitialMiniGameProps> = ({ type, players, onComplete }) => {
  const [playerIndex,setPlayerIndex]=useState(0); const [effects,setEffects]=useState<MiniGameEffect[]>([]); const [usedChoiceIndexes,setUsedChoiceIndexes]=useState<number[]>([]); const [revealedNote,setRevealedNote]=useState<string|null>(null); const [finishedPlayerTurn,setFinishedPlayerTurn]=useState(false);
  const choiceOutcomes=useMemo(()=>buildChoiceOutcomes(type,Math.max(4,players.length)),[type,players.length]); const higherLowerPrompts=useMemo(()=>shuffle(HIGHER_LOWER_PROMPTS),[]);
  const currentPlayer=players[playerIndex]; const currentPrompt=higherLowerPrompts[playerIndex%higherLowerPrompts.length]; if(!currentPlayer)return null;
  const [upperChoiceLabel,lowerChoiceLabel]=comparisonLabels(currentPrompt.prompt);
  const finishTurn=(effect:MiniGameEffect)=>{sound.playStamp();setEffects(prev=>[...prev,effect]);setRevealedNote(effect.note);setFinishedPlayerTurn(true)};
  const advance=()=>{sound.playClick();if(playerIndex+1>=players.length){onComplete(effects);return;}setPlayerIndex(v=>v+1);setRevealedNote(null);setFinishedPlayerTurn(false)};
  const choosePhysicalOption=(idx:number)=>{if(finishedPlayerTurn||usedChoiceIndexes.includes(idx))return;const outcome=choiceOutcomes[idx];setUsedChoiceIndexes(prev=>[...prev,idx]);finishTurn({playerId:currentPlayer.id,pointsDelta:outcome.pointsDelta,asset:outcome.asset,note:outcome.label})};
  const chooseHigherLower=(choice:'HIGHER'|'LOWER')=>{if(finishedPlayerTurn)return;const correct=currentPrompt.targetValue>currentPrompt.referenceValue?'HIGHER':'LOWER';const ok=choice===correct;finishTurn({playerId:currentPlayer.id,pointsDelta:ok?currentPrompt.reward:0,note:`${ok?`Correct: +${currentPrompt.reward} points.`:'Incorrect: 0 points.'} ${currentPrompt.explanation}`})};
  const chooseFileRisk=(risk:'SAFE'|'RISKY'|'QUESTIONABLE')=>{if(finishedPlayerTurn)return;const roll=Math.random();let pointsDelta=0,note='';if(risk==='SAFE'){pointsDelta=128;note='+128 points. Safe, dull and annoyingly sensible.';}else if(risk==='RISKY'){const ok=roll<.58;pointsDelta=ok?347:-64;note=ok?'+347 points. Risk has briefly mistaken you for someone competent.':'−64 points. Risk has returned to its normal duties.';}else{const ok=roll<.34;pointsDelta=ok?593:-137;note=ok?'+593 points. An appalling decision has somehow worked.':'−137 points. The Bureau would like to clarify that this outcome was extremely foreseeable.';}finishTurn({playerId:currentPlayer.id,pointsDelta,note})};
  const title=type==='RED_BUTTON'?'The Red Button Office':type==='FILE_CABINET'?'Unclaimed Filing Cabinet':type==='HIGHER_LOWER'?'Statistical Hunch Department':'Three Sealed Files';
  const subtitle=type==='RED_BUTTON'?'Each candidate gets one button. Once pressed, it is dead to everyone else.':type==='FILE_CABINET'?'Choose one remaining drawer. The Bureau denies placing anything interesting inside.':type==='HIGHER_LOWER'?'One judgement each. No timer, no handover race, just the possibility of public error.':'Choose Safe, Risky or Deeply Questionable. The labels are unusually accurate.';
  const art=type==='RED_BUTTON'?EVENT_ART.RED_BUTTON:type==='FILE_CABINET'?EVENT_ART.FILE_CABINET:type==='THREE_FILES'?EVENT_ART.THREE_FILES:undefined;

  return <div className="relative w-full max-w-5xl mx-auto overflow-hidden rounded-[28px] border-[4px] border-[#765139] px-3 py-5 font-['Plus_Jakarta_Sans'] shadow-2xl">
    <GeneratedArtBackdrop src={art} dim={0.5} animate />
    <div className="relative z-10 flex flex-col items-center gap-5">
      <div className="w-full rounded-2xl border-[3px] border-[#765139] bg-[#fff7df]/94 p-5 text-center shadow-[0_5px_0_#765139]"><div className="flex justify-center items-center gap-2 text-[#a9443d] mb-2">{type==='RED_BUTTON'?<CircleDot size={22}/>:type==='FILE_CABINET'?<FileArchive size={22}/>:type==='HIGHER_LOWER'?<Gauge size={22}/>:<ShieldQuestion size={22}/>}<span className="font-['Courier_Prime'] text-xs font-black tracking-[0.2em] uppercase">Unscheduled Bureau Event</span></div><h2 className="font-['Cinzel'] font-black text-2xl sm:text-3xl text-[#244b55]">{title}</h2><p className="font-['Fraunces'] text-sm text-[#6a543f] italic mt-1">{subtitle}</p></div>
      <div className="w-full max-w-2xl rounded-2xl border-[3px] border-[#765139] bg-[#fff7df]/94 p-5 shadow-[0_6px_0_#765139]">
        <div className="flex items-center gap-3 pb-4 border-b-2 border-[#c7a675]"><BureauAvatar player={currentPlayer} size={52}/><div><span className="font-['Courier_Prime'] text-[10px] uppercase tracking-widest text-[#a9443d] font-black">Candidate {playerIndex+1} of {players.length}</span><h3 className="font-['Cinzel'] text-lg font-black text-[#244b55]">{currentPlayer.name}</h3></div></div>
        {!finishedPlayerTurn&&(type==='RED_BUTTON'||type==='FILE_CABINET')&&<div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-5">{choiceOutcomes.slice(0,Math.max(4,players.length)).map((_,idx)=>{const used=usedChoiceIndexes.includes(idx);return <button key={idx} disabled={used} onClick={()=>choosePhysicalOption(idx)} className={`bureau-button bureau-mechanical min-h-28 rounded-xl border-2 flex flex-col items-center justify-center gap-2 ${used?'bg-[#cdbd9f] opacity-45':type==='RED_BUTTON'?'bg-[#d9644f] text-white':'bg-[#2f8f95] text-white'}`}>{type==='RED_BUTTON'?<CircleDot size={32}/>:<Archive size={30}/>}<span className="font-['Cinzel'] text-xs font-black uppercase tracking-wider">{type==='RED_BUTTON'?`Button ${idx+1}`:`Drawer ${String.fromCharCode(65+idx)}`}</span>{used&&<span className="font-['Courier_Prime'] text-[9px] uppercase">Taken</span>}</button>})}</div>}
        {!finishedPlayerTurn&&type==='HIGHER_LOWER'&&<div className="pt-5 flex flex-col gap-4"><div className="rounded-xl bg-[#e9ddbb] border-2 border-[#765139] p-4 text-center"><span className="font-['Courier_Prime'] text-[10px] text-[#775e47] uppercase block">Reference</span><strong className="font-['Cinzel'] text-lg text-[#244b55]">{currentPrompt.referenceLabel}</strong><span className="block font-['Space_Mono'] text-sm text-[#5e4f43]">{currentPrompt.referenceValue.toLocaleString()} {currentPrompt.unit}</span><p className="mt-3 font-['Fraunces'] text-base text-[#3f4d4e]">{currentPrompt.prompt}</p><strong className="block font-['Cinzel'] text-xl text-[#a9443d] mt-1">{currentPrompt.targetLabel}</strong></div><div className="grid grid-cols-2 gap-3"><button onClick={()=>chooseHigherLower('HIGHER')} className="bureau-button py-4 rounded-xl bg-[#4f7457] text-white font-['Cinzel'] font-black uppercase">{upperChoiceLabel}</button><button onClick={()=>chooseHigherLower('LOWER')} className="bureau-button py-4 rounded-xl bg-[#d9644f] text-white font-['Cinzel'] font-black uppercase">{lowerChoiceLabel}</button></div></div>}
        {!finishedPlayerTurn&&type==='THREE_FILES'&&<div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-5"><button onClick={()=>chooseFileRisk('SAFE')} className="bureau-button p-5 rounded-xl bg-[#4f7457] text-white text-left"><strong className="font-['Cinzel'] text-lg">Safe</strong><p className="text-xs mt-2">Guaranteed modest gain.</p></button><button onClick={()=>chooseFileRisk('RISKY')} className="bureau-button p-5 rounded-xl bg-[#e0a83f] text-[#463421] text-left"><strong className="font-['Cinzel'] text-lg">Risky</strong><p className="text-xs mt-2">58% chance of a strong reward.</p></button><button onClick={()=>chooseFileRisk('QUESTIONABLE')} className="bureau-button p-5 rounded-xl bg-[#7c5a91] text-white text-left"><strong className="font-['Cinzel'] text-lg">Deeply Questionable</strong><p className="text-xs mt-2">34% chance of a very large reward.</p></button></div>}
        {finishedPlayerTurn&&<div className="pt-5 flex flex-col items-center gap-4 text-center bureau-paper-drop"><div className="w-full rounded-xl border-2 border-[#765139] bg-[#efe0ba] p-5"><span className="font-['Courier_Prime'] text-[10px] text-[#a9443d] uppercase tracking-widest block mb-2">Outcome Filed</span><p className="font-['Fraunces'] text-base text-[#4d4238] leading-relaxed">{revealedNote}</p></div><button onClick={advance} className="bureau-button px-7 py-3 rounded-xl bg-[#376d9b] text-white font-['Cinzel'] font-black uppercase flex items-center gap-2">{playerIndex+1>=players.length?'Return to Assessment':'Next Candidate'}<ArrowRight size={16}/></button></div>}
      </div>
    </div>
  </div>;
};
