import { allChallenges } from '../src/data/questions';
import { difficultyDistribution,exposedAnswers } from '../src/data/editorial';
import { aggregateSimulations, simulateRoundBalance, simulateSeatBalance } from '../src/game/balance';
import { ALL_ROUND_TYPES } from '../src/game/match';
import { rivalryThreshold } from '../src/game/rivalry';
import { simulateThresholdRate } from '../src/game/balance';
import { readFileSync } from 'node:fs';
import { ROUND_DEV_SCENARIOS } from '../src/dev/roundDevScenarios';
import { VISUAL_ASSET_MANIFEST } from '../src/data/visualAssetManifest';
import { chainOfCommandChallenges, commonDossierChallenges, complaintsDeskChallenges, dispatchBoxChallenges, misfiledRecordsChallenges, missingMinutesChallenges, publicEnquiryChallenges, redactedRecordsChallenges, seatingCommitteeChallenges } from '../src/data/prototypeQuestions';
import { simulatePoliticsPower, simulateRiskStrategies, simulateScheduleVariety } from '../src/game/advancedBalance';
import { simulateFormatPacing } from '../src/game/pacing';

const leaks=allChallenges.flatMap(challenge=>exposedAnswers(challenge).map(answer=>`${challenge.id}: ${answer}`));
const balance=aggregateSimulations(5000,[{id:'new host',skill:.35},{id:'regular',skill:.6},{id:'expert',skill:.82}],ALL_ROUND_TYPES);
const roundBalance=simulateRoundBalance(5000,ALL_ROUND_TYPES);
const politicsThresholds=ALL_ROUND_TYPES.map(roundType=>({roundType,threshold:rivalryThreshold(roundType).value,successRate:Number(simulateThresholdRate(5000,roundType,rivalryThreshold(roundType).value).toFixed(3))}));
const seatBalance=[1,2,4].map(playerCount=>simulateSeatBalance(5000,playerCount as 1|2|4,ALL_ROUND_TYPES));
const riskStrategies=simulateRiskStrategies(8000);
const politicsPower=simulatePoliticsPower(5000);
const scheduleVariety=simulateScheduleVariety(3000);
const formatPacing=(['FIRST','QUICK','STANDARD','FULL'] as const).flatMap(preset=>[1,2,4].map(playerCount=>simulateFormatPacing(3000,preset,playerCount as 1|2|4,playerCount===1?'OFF':'STANDARD')));
const stylesheet=readFileSync(new URL('../src/index.css',import.meta.url),'utf8');
const pageZoomDeclarations=(stylesheet.match(/(?:^|[;{])\s*zoom\s*:/gm)??[]).length;
const artworkFiles=new Set(Object.values(VISUAL_ASSET_MANIFEST).flatMap(states=>Object.values(states).flatMap(asset=>asset?[asset.desktop,asset.compact]:[])));
console.log(JSON.stringify({questions:allChallenges.length,prototypeChallenges:{MISFILED_RECORDS:misfiledRecordsChallenges.length,REDACTED_RECORDS:redactedRecordsChallenges.length,COMMON_DOSSIER:commonDossierChallenges.length,MISSING_MINUTES:missingMinutesChallenges.length,PUBLIC_ENQUIRY:publicEnquiryChallenges.length,CHAIN_OF_COMMAND:chainOfCommandChallenges.length,COMPLAINTS_DESK:complaintsDeskChallenges.length,SEATING_COMMITTEE:seatingCommitteeChallenges.length,DISPATCH_BOX:dispatchBoxChallenges.length},difficulty:difficultyDistribution(allChallenges),exposedAnswers:leaks,balanceAverages:balance,roundBalance,politicsThresholds,politicsPower,riskStrategies,seatBalance,scheduleVariety,formatPacing,visualGalleryScenarios:ROUND_DEV_SCENARIOS.length,responsiveArtworkFiles:artworkFiles.size,pageZoomDeclarations},null,2));
const economyOutlier=roundBalance.some(round=>round.mean<475||round.mean>525);
const politicsOutlier=politicsThresholds.some(round=>round.successRate<=.25||round.successRate>=.75);
const seatOutlier=seatBalance.some(report=>{const mean=report.averages.reduce((sum,value)=>sum+value,0)/report.averages.length;return mean>0&&report.spread/mean>=.02;});
const riskTotals=riskStrategies.map(report=>report.meanTotal);
const strategyOutlier=Math.max(...riskTotals)/Math.min(...riskTotals)>=1.28;
const politicsReturns=politicsPower.map(report=>report.scorePerInfluence);
const politicsPowerOutlier=Math.max(...politicsReturns)/Math.min(...politicsReturns)>=1.6||politicsPower.some(report=>report.maximumScoreAwarded>150);
const scheduleOutlier=scheduleVariety.some(report=>report.adjacentSimilarityRate>0||report.meanDistinctRounds!==report.roundCount||report.meanClosingMomentum<=report.meanOpeningMomentum+.15);
const pacingOutlier=formatPacing.some(report=>report.lowerDecileMinutes<report.lowerMinutes||report.upperDecileMinutes>report.upperMinutes);
if(leaks.length||pageZoomDeclarations||economyOutlier||politicsOutlier||seatOutlier||strategyOutlier||politicsPowerOutlier||scheduleOutlier||pacingOutlier)process.exitCode=1;
